### ISSUE TITLE
Concurrent sample: intermittent failure

### ISSUE THREAD

**Issue by jaredthirsk** [ledjon-behluli/OrleanSpaces#1]
In SpaceTuple.cs, I modified to avoid crash: 

`public override string ToString() => fields == null ? "!! fields is null !!" : $"({string.Join(", ", fields)})";`

Run Concurrent:
```
...
READER 0: (exchange-key, 0)
READER 4: !! fields is null !!
READER 6: (exchange-key, 6)
...
```

Usually 1 or two Readers have null fields.

**Comment by ledjon-behluli** [comment]
Thank you, I'll have a look at ASAP
